In [5]:
import numpy as np
import tensorflow as tf

In [25]:
w = tf.Variable(0,dtype=tf.float32)
optimizer = tf.keras.optimizers.Adam(0.1)

def train_step():
    with tf.GradientTape() as tape:
        cost = w**2 - 10*w + 25
    trainable_variables = [w]
    grads = tape.gradient(cost,trainable_variables)
    optimizer.apply_gradients(zip(grads,trainable_variables))
    
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


In [6]:
tf.__version__

'2.10.0'

In [3]:
train_step()
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.09999997>


In [4]:
for i in range(1000):
    train_step()
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.000001>


In [12]:
w = tf.Variable(0,dtype=tf.float32)
x = np.array([1.0,-10.0,25.0],dtype=np.float32)
optimizer = tf.keras.optimizers.Adam(0.1)
optimizer_rms = tf.keras.optimizers.RMSprop(0.1)

def training(x,w,optimizer):
    def cost_fn():
        return x[0]*w**2 + x[1]*w + x[2]
    for i in range(1000):
        optimizer.minimize(cost_fn,[w])
    
    return w

w = training(x,w,optimizer_rms)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>


In [19]:
1-(10**(-np.random.rand()+1))

-6.845770287443679

In [7]:
 len(tf.config.list_physical_devices('GPU'))

0

In [8]:
tf.config.list_physical_devices('GPU')

[]

In [22]:
label = tf.constant(1)
label_2 = [2]
depth = 4

In [23]:
a = tf.one_hot(label_2,depth,axis=0)
a

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       [0.]], dtype=float32)>

In [24]:
tf.reshape(a,[-1])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 1., 0.], dtype=float32)>